"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Comment = { id: string; body: string; author?: string | null; handle?: string | null; revisionNumber: number; createdAt?: string };
type Suggestion = { id: string; body: string; suggestionType: string; status: string; author?: string | null; handle?: string | null; revisionNumber: number; resolutionNote?: string | null };
const starterComments: Comment[] = [
  { id: "starter-1", body: "The version boundary makes this much easier to enter as a reader. I would be curious to see the strongest disagreement in the next revision.", author: "Community reader", handle: "reader-one", revisionNumber: 3 },
  { id: "starter-2", body: "The distinction between a plan surviving and a plan winning is a useful one for new debaters.", author: "Mira", handle: "mira", revisionNumber: 3 },
];

export default function AnalysisDiscussion({ analysisId, revisionNumber }: { analysisId: string; revisionNumber: string }) {
  const [comments, setComments] = useState<Comment[]>(starterComments); const [body, setBody] = useState(""); const [suggestionBody, setSuggestionBody] = useState(""); const [suggestionType, setSuggestionType] = useState("clarification"); const [suggestions, setSuggestions] = useState<Suggestion[]>([]); const [message, setMessage] = useState(""); const [posting, setPosting] = useState(false);
  useEffect(() => { fetch(`/api/analyses/${analysisId}/comments`).then((response) => response.ok ? response.json() as Promise<{ comments?: Comment[] }> : Promise.reject()).then((data) => { if (data.comments?.length) setComments(data.comments); }).catch(() => undefined); }, [analysisId]);
  async function post(event: FormEvent) { event.preventDefault(); setPosting(true); setMessage(""); try { const csrf = await fetch("/api/auth/csrf").then((response) => response.json() as Promise<{ csrfToken?: string }>); const response = await fetch(`/api/analyses/${analysisId}/comments`, { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrf.csrfToken ?? "" }, body: JSON.stringify({ body, revisionNumber: Number(revisionNumber) }) }); const data = await response.json() as { comment?: Comment; error?: { message?: string } }; if (!response.ok) throw new Error(data.error?.message ?? "Sign in to join the discussion."); if (data.comment) setComments((current) => [...current, data.comment as Comment]); setBody(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Comment could not be posted."); } finally { setPosting(false); } }
  async function suggest(event: FormEvent) { event.preventDefault(); setPosting(true); setMessage(""); try { const csrf = await fetch("/api/auth/csrf").then((response) => response.json() as Promise<{ csrfToken?: string }>); const response = await fetch(`/api/analyses/${analysisId}/suggestions`, { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrf.csrfToken ?? "" }, body: JSON.stringify({ suggestionType, body: suggestionBody, revisionNumber: Number(revisionNumber) }) }); const data = await response.json() as { suggestion?: Suggestion; error?: { message?: string } }; if (!response.ok) throw new Error(data.error?.message ?? "Sign in with a verified email to suggest a review."); if (data.suggestion) setSuggestions((current) => [...current, data.suggestion as Suggestion]); setSuggestionBody(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Suggestion could not be posted."); } finally { setPosting(false); } }
  return <section className="analysis-discussion" aria-labelledby="discussion-title"><div className="discussion-heading"><div><span className="card-label">REVISION {revisionNumber} / READER REVIEW</span><h2 id="discussion-title">Leave the argument better than you found it.</h2></div><span>{comments.length} comments</span></div><div className="discussion-grid"><div className="comment-list">{comments.map((comment) => <article className="comment-card" key={comment.id}><div><strong>{comment.author ?? "Reader"}</strong><span>@{comment.handle ?? "community"} · revision {comment.revisionNumber}</span></div><p>{comment.body}</p></article>)}{suggestions.map((suggestion) => <article className="comment-card" key={suggestion.id}><div><strong>Review suggestion</strong><span>{suggestion.suggestionType} · {suggestion.status}</span></div><p>{suggestion.body}</p></article>)}</div><div className="comment-form"><form onSubmit={post}><label htmlFor="analysis-comment">Add context, a counter-reading, or a source question.<textarea id="analysis-comment" value={body} onChange={(event) => setBody(event.target.value)} minLength={2} maxLength={2000} required placeholder="Keep the conversation specific and useful…" rows={6} /></label><button className="button button-primary" disabled={posting} type="submit">{posting ? "Posting…" : "Post comment ↗"}</button></form><form onSubmit={suggest}><label htmlFor="suggestion-type">Suggest an improvement<select id="suggestion-type" value={suggestionType} onChange={(event) => setSuggestionType(event.target.value)}><option value="clarification">Request clarification</option><option value="correction">Suggest a correction</option><option value="source_request">Request source support</option></select></label><textarea aria-label="Review suggestion" value={suggestionBody} onChange={(event) => setSuggestionBody(event.target.value)} minLength={5} maxLength={2000} required placeholder="Point to a specific block or claim…" rows={4} /><button className="button button-outline" disabled={posting} type="submit">Send review suggestion</button></form>{message && <p className="form-error" role="alert">{message} <Link href="/auth/sign-in">Sign in</Link></p>}<small>Comments and suggestions attach to this revision. They do not silently change the author’s text.</small></div></div></section>;
}
