"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { ResearchAnalysis } from "../../lib/analysis-catalog";
import AnalysisDiscussion from "./analysis-discussion";

export default function AnalysisDetailClient({ initialEntry }: { initialEntry: ResearchAnalysis }) {
  const [entry, setEntry] = useState(initialEntry);
  useEffect(() => { fetch(`/api/analyses/${initialEntry.slug}`).then((response) => response.ok ? response.json() as Promise<{ analysis?: Partial<ResearchAnalysis> & { id?: string; currentRevision?: number } }> : Promise.reject()).then(async (data) => { if (data.analysis) { let comments = data.analysis.comments ?? 0; if (data.analysis.id) { const commentResponse = await fetch(`/api/analyses/${data.analysis.id}/comments`); if (commentResponse.ok) { const commentData = await commentResponse.json() as { comments?: unknown[] }; comments = commentData.comments?.length ?? comments; } } setEntry({ ...initialEntry, ...data.analysis, tags: data.analysis.tags ?? initialEntry.tags, revision: String(data.analysis.currentRevision ?? initialEntry.revision).padStart(2, "0"), author: data.analysis.author ?? "Community researcher", readTime: data.analysis.readTime ?? "Open study", comments, status: "published" }); } }).catch(() => undefined); }, [initialEntry]);
  return <><div className="analysis-layout"><article className="analysis-body"><div className="analysis-meta"><span>REVISION {entry.revision}</span><span>{entry.domain} / {entry.subjectType.toUpperCase()}</span><span>{entry.status === "published" ? "PUBLIC RESEARCH" : "PRIVATE DRAFT"}</span></div><div className="analysis-subject-banner"><span>{entry.subjectType === "aspect" ? "ASPECT STUDY" : entry.subjectType.toUpperCase()}</span><strong>{entry.subjectLabel}</strong><small>{entry.aspect}</small></div><h2>What changes when the argument has a memory?</h2><p>{entry.summary}</p><p>The useful question is not whether a character is simply “smarter” or a work simply “better.” It is which decisions, patterns, and effects remain available after the context changes—and which details a reader can check for themselves.</p><blockquote>“A conclusion is stronger when the reader can see what would falsify it.”</blockquote><p>ScaleFrame treats reasoning as an inspectable object. Each paragraph can point back to a claim, a source reference, and the version boundary that makes the claim meaningful.</p><div className="citation-box"><span>RESEARCH TRAIL / LINKED CLAIM</span><strong>Every strong reading leaves a path from observation to interpretation.</strong><small>Evidence · source context · version boundary · confidence label</small></div></article><aside className="detail-card analysis-rail"><span className="card-label">RESEARCH INDEX</span><div className="data-list"><div><span>Lens</span><b>{entry.domain}</b></div><div><span>Reading time</span><b>{entry.readTime}</b></div><div><span>Revision</span><b>{entry.revision}</b></div><div><span>Discussion</span><b>{entry.comments} comments</b></div><div><span>Author</span><b>{entry.author}</b></div></div><div className="tag-row analysis-tags">{entry.tags.map((itemTag) => <span key={itemTag}>#{itemTag}</span>)}</div><span className="card-label">READER REVIEW</span><p>Comments attach to a revision, keeping the author’s text stable while the community adds context.</p><Link className="button button-outline" href={`/auth/sign-in?next=/analysis/${entry.slug}`}>Sign in to join discussion ↗</Link><Link className="text-link" href="/analysis/new">Start a related study ↗</Link><Link className="text-link" href="/comparisons/baku-vs-johan-strategists-ceiling">View source comparison ↗</Link></aside></div><AnalysisDiscussion analysisId={entry.id} revisionNumber={entry.revision} /></>;
}
