import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { accounts, analyses, analysisComments, analysisClaims, analysisRevisions, analysisSourceCards, analysisSuggestions, claims, comparisons, comparisonCollaborationRequests, comparisonRevisions, evidence, expertiseFacets, metricProposals, notifications, profiles, studioProjects } from "../../../../db/schema";
import { getCurrentUser } from "../../../../lib/auth";
import { errorResponse } from "../../../../lib/http";
import { writeAudit } from "../../../../lib/security";

export async function GET(request: Request) {
  const user = await getCurrentUser(request); if (!user) return errorResponse("Sign in to export your data.", 401, "authentication_required");
  try {
    const db = getDb(); const [account, profile, facets, userComparisons, comparisonHistory, userClaims, userEvidence, userAnalyses, allAnalysisRevisions, allSources, allAnalysisClaims, comments, suggestions, proposals, projects, userNotifications, collaborationRequests] = await Promise.all([db.select().from(accounts).where(eq(accounts.id, user.subject)), db.select().from(profiles).where(eq(profiles.accountId, user.subject)), db.select().from(expertiseFacets).where(eq(expertiseFacets.accountId, user.subject)), db.select().from(comparisons).where(eq(comparisons.ownerAccountId, user.subject)), db.select().from(comparisonRevisions).where(eq(comparisonRevisions.createdByAccountId, user.subject)), db.select().from(claims).where(eq(claims.ownerAccountId, user.subject)), db.select().from(evidence).where(eq(evidence.ownerAccountId, user.subject)), db.select().from(analyses).where(eq(analyses.ownerAccountId, user.subject)), db.select().from(analysisRevisions), db.select().from(analysisSourceCards), db.select().from(analysisClaims), db.select().from(analysisComments).where(eq(analysisComments.authorAccountId, user.subject)), db.select().from(analysisSuggestions).where(eq(analysisSuggestions.authorAccountId, user.subject)), db.select().from(metricProposals).where(eq(metricProposals.proposerAccountId, user.subject)), db.select().from(studioProjects).where(eq(studioProjects.ownerAccountId, user.subject)), db.select().from(notifications).where(eq(notifications.accountId, user.subject)), db.select().from(comparisonCollaborationRequests).where(eq(comparisonCollaborationRequests.requesterAccountId, user.subject))]);
    const analysisIds = new Set(userAnalyses.map((analysis) => analysis.id)); await writeAudit(user.subject, "account_exported", "account", user.subject);
    const payload = { exportedAt: new Date().toISOString(), account, profile, expertiseFacets: facets, comparisons: userComparisons, comparisonRevisions: comparisonHistory, claims: userClaims, evidence: userEvidence, analyses: userAnalyses, analysisRevisions: allAnalysisRevisions.filter((item) => analysisIds.has(item.analysisId)), analysisSourceCards: allSources.filter((item) => analysisIds.has(item.analysisId)), analysisClaims: allAnalysisClaims.filter((item) => analysisIds.has(item.analysisId)), analysisComments: comments, analysisSuggestions: suggestions, metricProposals: proposals, studioProjects: projects, notifications: userNotifications, comparisonCollaborationRequests: collaborationRequests };
    return new Response(JSON.stringify(payload, null, 2), { status: 200, headers: { "content-type": "application/json; charset=utf-8", "content-disposition": `attachment; filename="scaleframe-export-${user.subject}.json"`, "cache-control": "no-store" } });
  } catch { return errorResponse("Your export is temporarily unavailable.", 503, "database_unavailable"); }
}
