import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { accounts, analyses, analysisRevisions, claims, comparisons, comparisonRevisions, evidence, expertiseFacets, metricProposals, notifications, profiles, studioProjects } from "../../../../db/schema";
import { getCurrentUser } from "../../../../lib/auth";
import { errorResponse } from "../../../../lib/http";
import { writeAudit } from "../../../../lib/security";

export async function GET(request: Request) {
  const user = await getCurrentUser(request); if (!user) return errorResponse("Sign in to export your data.", 401, "authentication_required");
  try { const db = getDb(); const [account, profile, facets, userComparisons, revisions, userClaims, userEvidence, userAnalyses, analysisHistory, proposals, projects, userNotifications] = await Promise.all([db.select().from(accounts).where(eq(accounts.id, user.subject)), db.select().from(profiles).where(eq(profiles.accountId, user.subject)), db.select().from(expertiseFacets).where(eq(expertiseFacets.accountId, user.subject)), db.select().from(comparisons).where(eq(comparisons.ownerAccountId, user.subject)), db.select().from(comparisonRevisions).where(eq(comparisonRevisions.createdByAccountId, user.subject)), db.select().from(claims).where(eq(claims.ownerAccountId, user.subject)), db.select().from(evidence).where(eq(evidence.ownerAccountId, user.subject)), db.select().from(analyses).where(eq(analyses.ownerAccountId, user.subject)), db.select().from(analysisRevisions), db.select().from(metricProposals).where(eq(metricProposals.proposerAccountId, user.subject)), db.select().from(studioProjects).where(eq(studioProjects.ownerAccountId, user.subject)), db.select().from(notifications).where(eq(notifications.accountId, user.subject))]); await writeAudit(user.subject, "account_exported", "account", user.subject); const payload = { exportedAt: new Date().toISOString(), account, profile, expertiseFacets: facets, comparisons: userComparisons, comparisonRevisions: revisions, claims: userClaims, evidence: userEvidence, analyses: userAnalyses, analysisRevisions: analysisHistory.filter((item) => userAnalyses.some((analysis) => analysis.id === item.analysisId)), metricProposals: proposals, studioProjects: projects, notifications: userNotifications }; return new Response(JSON.stringify(payload, null, 2), { status: 200, headers: { "content-type": "application/json; charset=utf-8", "content-disposition": `attachment; filename="scaleframe-export-${user.subject}.json"`, "cache-control": "no-store" } }); } catch { return errorResponse("Your export is temporarily unavailable.", 503, "database_unavailable"); }
}
