"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

type Mode = "sign-in" | "sign-up" | "forgot" | "reset";

export function AuthClient({ mode }: { mode: Mode }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const isForgot = mode === "forgot"; const isReset = mode === "reset"; const isSignUp = mode === "sign-up";
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setMessage("");
    const endpoint = isForgot ? "/api/auth/password-reset" : isReset ? "/api/auth/password-update" : isSignUp ? "/api/auth/sign-up" : "/api/auth/sign-in";
    const body = isReset ? { password } : isForgot ? { email } : { email, password };
    try { const csrf = isReset ? await fetch("/api/auth/csrf").then((response) => response.json() as Promise<{ csrfToken: string }>) : null; const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json", ...(csrf ? { "x-csrf-token": csrf.csrfToken } : {}) }, body: JSON.stringify(body) }); const data = await response.json() as { error?: { message?: string }; verificationRequired?: boolean }; if (!response.ok) throw new Error(data.error?.message || "Something went wrong."); if (isSignUp && data.verificationRequired) setMessage("Check your email to verify the account, then sign in."); else if (isForgot) setMessage("If that address exists, a reset link is on its way."); else if (isReset) setMessage("Your password was updated. You can sign in now."); else window.location.assign("/"); } catch (error) { setMessage(error instanceof Error ? error.message : "Something went wrong."); } finally { setBusy(false); }
  }
  const title = mode === "sign-in" ? "Welcome back." : isSignUp ? "Make an account." : isForgot ? "Recover access." : "Set a new password.";
  return <main className="auth-main"><div className="auth-card"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true"><i /><i /></span><span>SCALE<span>FRAME</span></span></Link><span className="card-label">ACCOUNT / SECURE ACCESS</span><h1>{title}</h1><p>{isSignUp ? "Create an account to save drafts, publish comparisons, and keep your work attached to its evidence." : isForgot ? "We will send a recovery link if the address is registered." : isReset ? "Choose a strong password for your ScaleFrame account." : "Public reading is open. Sign in when you are ready to make or save work."}</p><form onSubmit={submit}>{!isReset && <label className="form-label" htmlFor="auth-email">Email<input className="form-input" id="auth-email" type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label>}{!isForgot && <label className="form-label" htmlFor="auth-password">{isReset ? "New password" : "Password"}<input className="form-input" id="auth-password" type="password" autoComplete={isSignUp ? "new-password" : "current-password"} minLength={10} required value={password} onChange={(event) => setPassword(event.target.value)} /></label>}<button className="button button-primary auth-submit" disabled={busy} type="submit">{busy ? "Working…" : isForgot ? "Send recovery link" : isReset ? "Update password" : isSignUp ? "Create account" : "Sign in"}</button>{message && <p className="auth-message" role="status">{message}</p>}</form>{(mode === "sign-in" || mode === "sign-up") && <a className="button button-outline auth-google" href="/api/auth/google?next=/">Continue with Google ↗</a>}<div className="auth-links">{mode === "sign-in" && <><Link href="/auth/forgot-password">Forgot password?</Link><Link href="/auth/sign-up">Create account</Link></>}{mode === "sign-up" && <Link href="/auth/sign-in">Already have an account?</Link>}{isForgot && <Link href="/auth/sign-in">Back to sign in</Link>}{isReset && <Link href="/auth/sign-in">Back to sign in</Link>}</div><small className="form-hint">By continuing, you agree to use ScaleFrame in good faith. Accounts are 13+ and content labels apply.</small></div></main>;
}
