import Link from "next/link";
import { seedCharacters, seedComparisons, seedMetrics, seedWorks } from "../db/seed-data";
import { SiteShell } from "./site-shell";

export function PublicPage({ eyebrow, title, description, active = "" , children }: { eyebrow: string; title: string; description: string; active?: string; children: React.ReactNode }) {
  return <SiteShell active={active}>
    <main className="page-main section-pad">
      <div className="section-kicker"><span>{eyebrow}</span><span>ENGLISH / PUBLIC READ</span></div>
      <header className="page-heading"><div><h1>{title}</h1><p>{description}</p></div><Link className="button button-primary" href="/#new-comparison">Create a draft ↗</Link></header>
      {children}
    </main>
  </SiteShell>;
}

export function ExplorePage() {
  return <PublicPage active="explore" eyebrow="EXPLORE / KNOWLEDGE GRAPH" title="Find the argument behind the score." description="Browse published comparisons, evidence trails, metric definitions, and analysis written for readers who want to inspect the work." >
    <section className="page-grid page-grid-wide"><div>
      <div className="list-heading"><span>RECENT PUBLISHED WORK</span><span>{seedComparisons.length} indexed</span></div>
      {seedComparisons.map((item, index) => <Link className="recent-row" href={`/comparisons/${item.slug}`} key={item.slug}><span className="recent-index">0{index + 1}</span><div className="recent-main"><div><span className="status-chip">{item.domain}</span><span className="recent-age">SEEDED FOUNDATION</span></div><h3>{item.title}</h3><p>{item.categories} metrics · {item.evidence} evidence objects · {item.difficulty}</p></div><span className="recent-result">{item.winner}</span></Link>)}
    </div><aside className="review-rail"><div className="list-heading"><span>REVIEW QUEUE</span><span className="queue-count">03</span></div><div className="review-item review-cyan"><span className="review-icon">↳</span><div><strong>Evidence dispute</strong><p>Source context needs a clearer boundary.</p><span className="review-state">OPEN FOR REVIEW</span></div></div><div className="review-item review-wine"><span className="review-icon">◇</span><div><strong>Metric duplicate</strong><p>Counter-planning resembles planning.</p><span className="review-state">TRIAGE</span></div></div><div className="review-item review-orange"><span className="review-icon">+</span><div><strong>New community edit</strong><p>A reader suggested a counterargument.</p><span className="review-state">READY</span></div></div></aside></section>
    <section className="catalog-strip"><span>CATALOG SCOPE</span><strong>{seedWorks.length} works</strong><strong>{seedCharacters.length} characters</strong><strong>{seedMetrics.length} metric definitions</strong><Link href="/library">Open the Library ↗</Link></section>
  </PublicPage>;
}

export function LibraryPage() {
  return <PublicPage active="library" eyebrow="LIBRARY / UNIFIED SEARCH" title="A shared context layer for writing." description="Canonical metadata, community claims, versions, sources, and creative outputs stay linked without pretending they are the same kind of truth." >
    <div className="library-filters"><input className="library-search" placeholder="Search works, characters, metrics, comparisons, and analysis" aria-label="Search the Library" /><select aria-label="Filter by domain"><option>All domains</option><option>WIS / Powerscaling</option><option>SCD / Smart Character Debate</option><option>WW / Writing Wise</option></select><select aria-label="Filter by content type"><option>All content</option><option>Published comparisons</option><option>Metrics</option><option>Evidence</option><option>Analysis</option></select></div>
    <div className="library-catalog"><div className="catalog-column"><div className="list-heading"><span>WORKS</span><span>CANONICAL METADATA</span></div>{seedWorks.map((work) => <Link className="catalog-card" key={work.slug} href={`/works/${work.slug}`}><span className={`work-dot ${work.accent}`} /><div><strong>{work.title}</strong><p>{work.type} · {work.creator}</p><small>{work.description}</small></div><span>↗</span></Link>)}</div><div className="catalog-column"><div className="list-heading"><span>METRICS</span><span>VERSIONED</span></div>{seedMetrics.map((metric) => <Link className="catalog-card" key={metric.slug} href={`/metrics/${metric.slug}`}><span className="metric-code">{metric.domain}</span><div><strong>{metric.name}</strong><p>{metric.family} · weight {metric.defaultWeight.toFixed(1)}</p><small>{metric.definition}</small></div><span>↗</span></Link>)}</div></div>
  </PublicPage>;
}

export function MetricPage({ slug }: { slug: string }) {
  const metric = seedMetrics.find((item) => item.slug === slug) ?? seedMetrics[0];
  return <PublicPage eyebrow={`METRIC / ${metric.domain}`} title={metric.name} description={metric.definition} active="library">
    <div className="detail-grid"><article className="detail-card"><span className="card-label">DEFINITION / VERSION 1</span><h2>{metric.name}</h2><p>{metric.definition}</p><div className="data-list"><div><span>Domain</span><b>{metric.domain}</b></div><div><span>Family</span><b>{metric.family}</b></div><div><span>Default weight</span><b>{metric.defaultWeight.toFixed(1)} normalized units</b></div><div><span>Status</span><b>{metric.status}</b></div></div></article><aside className="detail-card accent-card"><span className="card-label">GOVERNANCE</span><h3>What this includes</h3><p>Published definitions are immutable. A future revision must preserve the old version for existing comparisons and explain what changed.</p><ul><li>Inclusion and exclusion criteria</li><li>Examples and anti-examples</li><li>Review history and duplicate checks</li><li>Transparent weight distribution</li></ul><Link className="text-link" href="/metrics">Browse all metrics ↗</Link></aside></div>
  </PublicPage>;
}

export function ComparisonPage({ slug }: { slug: string }) {
  const item = seedComparisons.find((comparison) => comparison.slug === slug) ?? seedComparisons[0];
  return <PublicPage eyebrow={`COMPARISON / ${item.domain}`} title={item.title} description="A public, versioned comparison with explicit rules, visible weights, evidence links, and a recalculable result." active="compare">
    <div className="detail-grid"><article className="detail-card comparison-detail"><div className="result-banner"><span>DECLARED RESULT</span><strong>{item.winner}</strong><b>{item.scoreA || "—"} / {item.scoreB || "—"}</b></div><div className="data-list"><div><span>Domain</span><b>{item.domain}</b></div><div><span>Format</span><b>{item.difficulty}</b></div><div><span>Metric categories</span><b>{item.categories}</b></div><div><span>Evidence objects</span><b>{item.evidence}</b></div><div><span>Formula</span><b>Σ(weight × normalized score)</b></div></div><Link className="button button-primary" href="/#workspace">Open comparison ledger ↗</Link></article><aside className="detail-card"><span className="card-label">PUBLISH CHECKLIST</span><ul className="check-list"><li>Explicit participant versions</li><li>Rules and assumptions declared</li><li>Metric definitions and weights visible</li><li>Evidence and counterarguments attached</li><li>Spoiler and content labels set</li></ul><Link className="text-link" href="/analysis/strategist-ceiling">Read linked analysis ↗</Link></aside></div>
  </PublicPage>;
}

export function AnalysisPage({ slug }: { slug: string }) {
  return <PublicPage eyebrow="ANALYSIS / VERSIONED WRITING" title={slug === "strategist-ceiling" ? "The strategist's ceiling" : "Analysis workspace"} description="A versioned essay layer connected to the comparison, its evidence, and reader review comments." active="analysis">
    <div className="analysis-layout"><article className="analysis-body"><div className="analysis-meta"><span>REVISION 03</span><span>WW / SCD</span><span>PUBLIC DRAFT</span></div><h2>What changes when the argument has a memory?</h2><p>The useful question is not whether a character is simply “smarter.” It is which decisions remain available after the other side changes the information state.</p><p>ScaleFrame treats that reasoning as an inspectable object. Each paragraph can point back to a claim, a source reference, and the version boundary that makes the claim meaningful.</p><blockquote>“A conclusion is stronger when the reader can see what would falsify it.”</blockquote><p>This is the first writing surface: focused, revision-aware, and deliberately single-owner. Public readers can leave review suggestions without silently changing the author’s work.</p><div className="citation-box"><span>LINKED CLAIM</span><strong>Counter-planning preserves the line after the first model breaks.</strong><small>Evidence · Usogui / Kagerou Club arc · source reference pending</small></div></article><aside className="detail-card"><span className="card-label">READER REVIEW</span><p>Comments and suggestions attach to a revision, not an invisible live document.</p><button className="button button-outline" type="button">Sign in to suggest an edit</button><Link className="text-link" href="/comparisons/baku-vs-johan-strategists-ceiling">View source comparison ↗</Link></aside></div>
  </PublicPage>;
}

export function StudioPage() {
  return <PublicPage eyebrow="STUDIO / COMPARISON CARDS" title="Turn the ledger into a shareable card." description="The first production Studio milestone is a 9:16 data-bound composer. Rendering can arrive later without changing the project schema." active="studio">
    <div className="studio-layout"><div className="studio-preview"><div className="studio-label">SCALEFRAME / SCD / 9:16</div><div className="studio-card"><span>THE STRATEGIST&apos;S CEILING</span><strong>BAKU<br /><em>vs</em> JOHAN</strong><div className="studio-winner">BAKU WINS / 61 — 39</div><small>DATA-BOUND COMPARISON CARD</small></div><div className="studio-controls"><button type="button">▣ Text</button><button type="button">▤ Comparison</button><button type="button">□ Shape</button><button type="button">◌ Caption</button></div></div><aside className="studio-sidebar"><div className="list-heading"><span>LAYERS</span><span>9:16</span></div>{["Title · bound", "Participant names · bound", "Weighted score · bound", "Winner band · bound", "Evidence note"].map((layer, index) => <div className="layer-row" key={layer}><span>{index + 1}</span><strong>{layer}</strong><small>◉</small></div>)}<div className="notice">Sign in to create a private project. Autosave, revision recovery, provenance metadata, and signed media uploads are part of the project API.</div><Link className="button button-primary" href="/settings">Configure account ↗</Link></aside></div>
  </PublicPage>;
}

export function SettingsPage() {
  return <PublicPage eyebrow="ACCOUNT / SECURITY" title="Your work stays yours." description="Accounts unlock private drafts, saved items, analysis revisions, Studio projects, and export/delete controls." >
    <div className="settings-grid"><article className="detail-card"><span className="card-label">AUTHENTICATION</span><h2>Sign in to participate.</h2><p>The Site is public-read by design. Supabase Auth will handle email verification, Google OAuth, password recovery, sessions, and optional authenticator MFA.</p><div className="form-group"><label className="form-label" htmlFor="email">Email</label><input className="form-input" id="email" type="email" placeholder="you@example.com" /></div><div className="form-row"><button className="button button-primary" type="button">Continue with email</button><button className="button button-outline" type="button">Continue with Google</button></div><small className="form-hint">Authentication configuration is intentionally server-side. Add the Supabase environment values before enabling writes in production.</small></article><aside className="detail-card"><span className="card-label">DATA RIGHTS</span><h3>Export or delete</h3><p>When signed in, these controls cover profile data, comparisons, analyses, comments, saved items, notifications, projects, and uploaded assets.</p><div className="settings-actions"><button className="button button-outline" type="button">Request export</button><button className="button button-quiet" type="button">View sessions</button></div><Link className="text-link" href="/moderation">Trust & safety ↗</Link></aside></div>
  </PublicPage>;
}

export function ModerationPage() {
  return <PublicPage eyebrow="TRUST & SAFETY / HUMAN REVIEW" title="Good faith needs structure." description="Reports, evidence disputes, metric review, takedown requests, and moderation actions are logged and reversible where appropriate." >
    <div className="detail-grid"><article className="detail-card"><span className="card-label">COMMUNITY GUIDELINES</span><h2>Argue the work. Show the receipt.</h2><ul><li>Label spoilers, mature content, and adaptation boundaries.</li><li>Separate canon metadata from community interpretation.</li><li>Use sources and counterarguments for consequential claims.</li><li>Report harassment, impersonation, spam, copyright concerns, and unsafe media.</li></ul><button className="button button-primary" type="button">Sign in to file a report</button></article><aside className="detail-card"><span className="card-label">GOVERNANCE LOG</span><div className="audit-row"><b>Metric proposal</b><span>duplicate review → human review</span></div><div className="audit-row"><b>Evidence dispute</b><span>source context requested</span></div><div className="audit-row"><b>Upload provenance</b><span>attestation required</span></div><p className="form-hint">Automated signals can triage spam and duplicates. They do not decide truth or final moderation outcomes.</p></aside></div>
  </PublicPage>;
}
