import { eq, inArray } from "drizzle-orm";
import { getDb } from "../../../../db";
import { accounts, analyses, analysisRevisions, assets, auditEvents, claims, comparisonRevisions, comparisons, evidence, expertiseFacets, metricProposals, notifications, profiles, studioProjects } from "../../../../db/schema";
import { getCurrentUser } from "../../../../lib/auth";
import { errorResponse, jsonResponse, sameOrigin, validCsrf } from "../../../../lib/http";
import { applySupabaseHeaders, createRouteSupabaseClient } from "../../../../lib/supabase";

export async function POST(request: Request) {
  if (!sameOrigin(request) || !validCsrf(request)) return errorResponse("CSRF validation failed.", 403, "csrf_rejected"); const user = await getCurrentUser(request); if (!user) return errorResponse("Sign in to delete your account.", 401, "authentication_required"); const payload = await request.json().catch(() => null) as { confirmation?: unknown } | null; if (payload?.confirmation !== "DELETE") return errorResponse("Type DELETE to confirm account deletion.", 400, "confirmation_required");
  try { const db = getDb(); const userComparisons = await db.select({ id: comparisons.id }).from(comparisons).where(eq(comparisons.ownerAccountId, user.subject)); const comparisonIds = userComparisons.map((item) => item.id); const userAnalyses = await db.select({ id: analyses.id }).from(analyses).where(eq(analyses.ownerAccountId, user.subject)); const analysisIds = userAnalyses.map((item) => item.id); if (comparisonIds.length) { await db.delete(comparisonRevisions).where(inArray(comparisonRevisions.comparisonId, comparisonIds)); await db.delete(comparisons).where(inArray(comparisons.id, comparisonIds)); } if (analysisIds.length) { await db.delete(analysisRevisions).where(inArray(analysisRevisions.analysisId, analysisIds)); await db.delete(analyses).where(inArray(analyses.id, analysisIds)); } await db.delete(claims).where(eq(claims.ownerAccountId, user.subject)); await db.delete(evidence).where(eq(evidence.ownerAccountId, user.subject)); await db.delete(metricProposals).where(eq(metricProposals.proposerAccountId, user.subject)); await db.delete(studioProjects).where(eq(studioProjects.ownerAccountId, user.subject)); await db.delete(assets).where(eq(assets.ownerAccountId, user.subject)); await db.delete(notifications).where(eq(notifications.accountId, user.subject)); await db.delete(expertiseFacets).where(eq(expertiseFacets.accountId, user.subject)); await db.delete(profiles).where(eq(profiles.accountId, user.subject)); await db.update(accounts).set({ email: `deleted+${user.subject}@invalid.scaleframe`, deletedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).where(eq(accounts.id, user.subject)); await db.insert(auditEvents).values({ id: `audit_${crypto.randomUUID().replaceAll("-", "")}`, actorAccountId: user.subject, action: "account_deleted", targetType: "account", targetId: user.subject, metadataJson: JSON.stringify({ comparisonCount: comparisonIds.length, analysisCount: analysisIds.length }) }); const { client, responseHeaders } = createRouteSupabaseClient(request); await client.auth.signOut({ scope: "global" }); return applySupabaseHeaders(jsonResponse({ deleted: true }), responseHeaders); } catch { return errorResponse("Account deletion is temporarily unavailable.", 503, "database_unavailable"); }
}
