import { eq, inArray } from "drizzle-orm";
import { getDb } from "../../../../db";
import { accounts, analyses, analysisClaimSourceLinks, analysisClaims, analysisComments, analysisRevisions, analysisSourceCards, analysisSuggestions, assets, auditEvents, claims, comparisonRevisions, comparisons, evidence, expertiseFacets, metricProposals, notifications, profiles, studioProjects } from "../../../../db/schema";
import { getCurrentUser } from "../../../../lib/auth";
import { errorResponse, jsonResponse, sameOrigin, validCsrf } from "../../../../lib/http";
import { applySupabaseHeaders, createRouteSupabaseClient } from "../../../../lib/supabase";

export async function POST(request: Request) {
  if (!sameOrigin(request) || !validCsrf(request)) return errorResponse("CSRF validation failed.", 403, "csrf_rejected"); const user = await getCurrentUser(request); if (!user) return errorResponse("Sign in to delete your account.", 401, "authentication_required"); const payload = await request.json().catch(() => null) as { confirmation?: unknown } | null; if (payload?.confirmation !== "DELETE") return errorResponse("Type DELETE to confirm account deletion.", 400, "confirmation_required");
  try {
    const db = getDb(); const comparisonRows = await db.select({ id: comparisons.id }).from(comparisons).where(eq(comparisons.ownerAccountId, user.subject)); const comparisonIds = comparisonRows.map((row) => row.id); const analysisRows = await db.select({ id: analyses.id }).from(analyses).where(eq(analyses.ownerAccountId, user.subject)); const analysisIds = analysisRows.map((row) => row.id);
    if (comparisonIds.length) { await db.delete(comparisonRevisions).where(inArray(comparisonRevisions.comparisonId, comparisonIds)); await db.delete(comparisons).where(inArray(comparisons.id, comparisonIds)); }
    if (analysisIds.length) { const analysisClaimRows = await db.select({ id: analysisClaims.id }).from(analysisClaims).where(inArray(analysisClaims.analysisId, analysisIds)); const analysisClaimIds = analysisClaimRows.map((row) => row.id); if (analysisClaimIds.length) await db.delete(analysisClaimSourceLinks).where(inArray(analysisClaimSourceLinks.claimId, analysisClaimIds)); await db.delete(analysisComments).where(inArray(analysisComments.analysisId, analysisIds)); await db.delete(analysisSuggestions).where(inArray(analysisSuggestions.analysisId, analysisIds)); await db.delete(analysisClaims).where(inArray(analysisClaims.analysisId, analysisIds)); await db.delete(analysisSourceCards).where(inArray(analysisSourceCards.analysisId, analysisIds)); await db.delete(analysisRevisions).where(inArray(analysisRevisions.analysisId, analysisIds)); await db.delete(analyses).where(inArray(analyses.id, analysisIds)); }
    await db.delete(claims).where(eq(claims.ownerAccountId, user.subject)); await db.delete(evidence).where(eq(evidence.ownerAccountId, user.subject)); await db.delete(metricProposals).where(eq(metricProposals.proposerAccountId, user.subject)); await db.delete(studioProjects).where(eq(studioProjects.ownerAccountId, user.subject)); await db.delete(assets).where(eq(assets.ownerAccountId, user.subject)); await db.delete(notifications).where(eq(notifications.accountId, user.subject)); await db.delete(expertiseFacets).where(eq(expertiseFacets.accountId, user.subject)); await db.delete(profiles).where(eq(profiles.accountId, user.subject)); const now = new Date().toISOString(); await db.update(accounts).set({ email: `deleted+${user.subject}@invalid.scaleframe`, deletedAt: now, updatedAt: now }).where(eq(accounts.id, user.subject)); await db.insert(auditEvents).values({ id: `audit_${crypto.randomUUID().replaceAll("-", "")}`, actorAccountId: user.subject, action: "account_deleted", targetType: "account", targetId: user.subject, metadataJson: JSON.stringify({ comparisonCount: comparisonIds.length, analysisCount: analysisIds.length }) });
    const { client, responseHeaders } = createRouteSupabaseClient(request); await client.auth.signOut({ scope: "global" }); return applySupabaseHeaders(jsonResponse({ deleted: true }), responseHeaders);
  } catch { return errorResponse("Account deletion is temporarily unavailable.", 503, "database_unavailable"); }
}
