"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

export default function SettingsClient() {
  const [user, setUser] = useState<{ email: string | null } | null>(null); const [loaded, setLoaded] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/me").then((response) => response.json() as Promise<{ user?: { email: string | null } | null }>).then((data) => { setUser(data.user ?? null); setLoaded(true); }).catch(() => setLoaded(true)); }, []);
  async function signOut() { const csrf = await fetch("/api/auth/csrf").then((response) => response.json() as Promise<{ csrfToken: string }>); await fetch("/api/auth/sign-out", { method: "POST", headers: { "x-csrf-token": csrf.csrfToken } }); window.location.assign("/"); }
  async function deleteAccount() { if (window.prompt("Type DELETE to permanently delete your ScaleFrame account and authored records.") !== "DELETE") return; const csrf = await fetch("/api/auth/csrf").then((response) => response.json() as Promise<{ csrfToken: string }>); const response = await fetch("/api/me/delete", { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrf.csrfToken }, body: JSON.stringify({ confirmation: "DELETE" }) }); const data = await response.json() as { error?: { message?: string } }; if (!response.ok) setMessage(data.error?.message || "Deletion failed."); else window.location.assign("/"); }
  if (!loaded) return <div className="detail-card"><p>Loading account…</p></div>;
  if (!user) return <div className="settings-grid"><article className="detail-card"><span className="card-label">AUTHENTICATION</span><h2>Sign in to participate.</h2><p>The Site is public-read by design. Sign in to save drafts, publish comparisons, and manage your data.</p><div className="settings-actions"><Link className="button button-primary" href="/auth/sign-in">Sign in ↗</Link><Link className="button button-outline" href="/auth/sign-up">Create account</Link></div></article><aside className="detail-card"><span className="card-label">DATA RIGHTS</span><p>Signed-in authors can export or delete their ScaleFrame records from this page.</p></aside></div>;
  return <div className="settings-grid"><article className="detail-card"><span className="card-label">AUTHENTICATED ACCOUNT</span><h2>{user.email}</h2><p>Your account can create private drafts and publish comparisons after the structured checklist is complete.</p><div className="settings-actions"><Link className="button button-primary" href="/compare/new">New comparison ↗</Link><button className="button button-outline" type="button" onClick={signOut}>Sign out</button></div></article><aside className="detail-card"><span className="card-label">DATA RIGHTS</span><p>Export the records associated with this account, or delete the account and authored records.</p><div className="settings-actions"><a className="button button-outline" href="/api/me/export">Export JSON</a><button className="button button-quiet" type="button" onClick={deleteAccount}>Delete account</button></div>{message && <p className="auth-message" role="alert">{message}</p>}</aside></div>;
}
